databases:
  - name: budget
    databaseName: budget_db_wb1t
    user: budget_user

services:
  - type: web
    name: budget-buddy
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_db_wb1t
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
